### ISSUE TITLE
Unsupported field: InstantSeconds When Receiving statements

### ISSUE THREAD

**Issue by venkatapathy** [Apereo-Learning-Analytics-Initiative/OpenLRW#13]
Hi,
I was successfully able to deploy OpenLRW, Post an xAPI statement:

{
```
  "actor": {
    "name": "Sally Glider",
    "mbox": "mailto:sally@example.com"
  },
  "verb": {
    "id": "http://adlnet.gov/expapi/verbs/experienced",
    "display": { "en-US": "experienced" }
  },
  "object": {
    "id": "http://example.com/activities/solo-hang-gliding",
    "definition": {
      "name": { "en-US": "Solo Hang Gliding" }
    }
  }
}
```

I also verified that it is stored in the MongoDB. When I try to receive all the statements or one statement from the endpoint GET xAPI/statements I get the following error, as per the logs:

**java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.time.LocalDate.get0(LocalDate.java:680)
	at java.time.LocalDate.getLong(LocalDate.java:659)
	at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$InstantPrinterParser.format(DateTimeFormatterBuilder.java:3178)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at java.time.LocalDateTime.format(LocalDateTime.java:1752)
	at unicon.matthews.xapi.service.DefaultXapiToCaliperConversionService.toXapi(DefaultXapiToCaliperConversionService.java:610)
	at unicon.matthews.xapi.endpoint.XapiApiController.getStatements(XapiApiController.java:139)**

I think it is in the code: DefaultXapiToCaliperConversionService.java:610, some error during parsing the date. In the db the date is stored as  **"eventTime" : ISODate("2017-06-20T06:57:01.011Z")** .

Any solutions for this?

**Comment by gryglbrt** [comment]
Resolved with https://github.com/gryglbrt/OpenLRW/commit/36082ed83c00caeb9c9adc3dfb742cdfda340170
