### ISSUE TITLE
About how to initialize mongodb instance correctly

### ISSUE THREAD

**Issue by aroman-stratio** [Apereo-Learning-Analytics-Initiative/OpenLRW#26]
Hi, i am having problems to run the jar file with a mongo server running within a docker container.

This is my application.yaml file:

`# different mongo instance running within a docker container
spring.data.mongodb.host: 172.17.0.3
spring.data.mongodb.port: 27017

server.port: 9966
spring.profiles: default
matthews.security.jwt:
  tokenExpirationTime: 240 # Number of minutes
  refreshTokenExpTime: 360 # Minutes
  tokenIssuer: http://example.com
  tokenSigningKey: changeme
  
# Spring Actuator
# See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
# Disable by default all but info

endpoints:
  enabled: false
  info:
    enabled: true
    
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

matthews.users:
     encrypted: false
     adminuser : ${random.value}
     password: ${random.value}
     emailAddress: ${random.value}@unicon.net`

This is an output of my docker image running locally:

`...
2017-09-14T13:20:00.127+0000 [clientcursormon]  mapped:64
2017-09-14T13:20:00.127+0000 [clientcursormon]  connections:1
2017-09-14T13:24:30.926+0000 [initandlisten] connection accepted from 172.17.0.1:55338 #2 (2 connections now open)
2017-09-14T13:24:31.479+0000 [initandlisten] connection accepted from 172.17.0.1:55340 #3 (3 connections now open)
2017-09-14T13:24:31.504+0000 [conn3] assertion 13 not authorized for query on test.tenant ns:test.tenant query:{ name: "DEFAULT_TENANT" }
2017-09-14T13:24:31.504+0000 [conn3]  ntoskip:0 ntoreturn:-1
2017-09-14T13:24:31.579+0000 [conn3] end connection 172.17.0.1:55340 (2 connections now open)
2017-09-14T13:24:31.580+0000 [conn2] end connection 172.17.0.1:55338 (1 connection now open)
2017-09-14T13:25:00.137+0000 [clientcursormon] mem (MB) res:66 virt:212
2017-09-14T13:25:00.137+0000 [clientcursormon]  mapped:64
2017-09-14T13:25:00.137+0000 [clientcursormon]  connections:1

> exit
bye
2017-09-14T13:25:52.025+0000 [conn1] end connection 127.0.0.1:47006 (0 connections now open)
**WHAT IS MY IP?**
root@d97d64355595:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:03  
          **inet addr:172.17.0.3**  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:47 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:5978 (5.9 KB)  TX bytes:3315 (3.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:139 errors:0 dropped:0 overruns:0 frame:0
          TX packets:139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:17541 (17.5 KB)  TX bytes:17541 (17.5 KB)

root@d97d64355595:/# 
`

And i am getting this exception when i run the project:

`Caused by: com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized for query on test.tenant' on server 172.17.0.3:27017
	at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:131)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:303)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:209)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:496)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:482)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:482)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:79)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DBCollection.findOne(DBCollection.java:777)
	at com.mongodb.DBCollection.findOne(DBCollection.java:747)
	at com.mongodb.DBCollection.findOne(DBCollection.java:694)
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2143)
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2127)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:1901)
	... 165 more
`
I guess that another process needs to push some initial data to the mongo instance, isnt?
My question is, how do i do that initial push?

**Comment by aroman-stratio** [comment]
nevermind, i already solved my problem. I can build the jar file and tomcat runs fine.

I run the mongo instance without --auth, like this:

`$ docker run -ti --rm -p 30000:27017 -v /srv/mongo:/data/db -e MONGOD_OPTIONS='--nojournal --smallfiles --noprealloc' arkadi/mongodb /sbin/my_init -- bash -l`

Then i added this setting to application.yml

`# different mongo instance running within a docker container
spring.data.mongodb.host: 172.17.0.3
spring.data.mongodb.port: 27017`

mvn clean package spring-boot:run and voilá, i can see something on http://localhost:9966/info
