### ISSUE TITLE
JSON statement from Sakai failing

### ISSUE THREAD

**Issue by jonespm** [Apereo-Learning-Analytics-Initiative/OpenLRW#29]
When grading an assignment, the SakaiXAPI provider generates this json below and gets a 500 error back from OpenLRW. Other statements generated from this provider are accepted. This previously worked in OpenLRS. I'm not sure where the error is.

Stacktrace from OpenLRW
```
Caused by: java.lang.IllegalStateException: unicon.matthews.caliper.Agent@7c5a2157[
  id=<null>
  type=https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#agentaccount
  context=http://purl.imsglobal.org/ctx/caliper/v1/Context
  name=John Fitz Gerald
  description=<null>
  extensions={}
  dateCreated=<null>
  dateModified=<null>
]
	at unicon.matthews.caliper.Agent$Builder.build(Agent.java:216)
	at unicon.matthews.xapi.service.DefaultXapiToCaliperConversionService.fromXapi(DefaultXapiToCaliperConversionService.java:272)
	at unicon.matthews.xapi.endpoint.XapiApiController.postStatement(XapiApiController.java:93)
	... 117 common frames omitted

```

JSON from Sakai

```
{
  "actor": {
    "name": "John Fitz Gerald",
    "account": {
      "name": "",
      "homePage": ""
    },
    "objectType": "Agent"
  },
  "result": {
    "completion": true,
    "score": {
      "min": 0.0,
      "max": 111.0,
      "raw": 10.0
    }
  },
  "verb": {
    "id": "http:\/\/www.adlnet.gov\/expapi\/verbs\/scored"
  },
  "context": {
    "contextActivities": {
      "other": {
        "id": "http:\/\/adlnet.gov\/expapi\/activities\/assignment"
      }
    },
    "instructor": {
      "name": "The Instructor",
      "account": {
        "name": "instructor",
        "homePage": "http:\/\/localhost"
      },
      "objectType": "Agent"
    }
  },
  "object": {
    "definition": {
      "name": {
        "en-US": "User received a grade"
      },
      "description": {
        "en-US": "User received a grade for their assginment: Single File Only; Submission #: 0"
      },
      "type": "http:\/\/adlnet.gov\/expapi\/activities\/received-grade-assignment"
    },
    "id": "http:\/\/localhost\/portal\/assignment\/s\/87768560-45c3-4aa7-9a29-d012384fec11\/26c0b7e8-a08f-4f9e-96b7-ceb13c063a26\/b9dac0f7-a0ae-4779-b1c7-547fc2895b5b",
    "objectType": "Activity"
  },
  "timestamp": "2017-11-07T15:44:59-05:00"
}
```

**Comment by jonespm** [comment]
Comment from @gryglbrt 

The issue here is that the account values for name and homepage in the xapi statement are empty:

```
"actor": { 
"name": "John Fitz Gerald", 
"account": { 
"name": "", 
"homePage": "" 
}, 
"objectType": "Agent" 
}
```

name and homePage are required fields in the spec. OpenLRW excepts them as well so it rejects the message.

So maybe this is something that needs to be validated in the Sakai provider?
